### ISSUE TITLE
Do you have to update the client token everyday

### ISSUE THREAD

**Issue by ma-karai** [Bockiii/deezloadermx-docker#15]
Do you have to update the client token everyday or is there a way to automatically fetch it and keep it saved ?

**Comment by Bockiii** [comment]
You mean the login token? You shouldn't need to update that for months. Do you get login requests every time you open up deezloader?

**Comment by ma-karai** [comment]
everytime i open the settings its empty and no automatical login takes place

**Comment by Bockiii** [comment]
do you have the config folder mapped to a local folder? do you have write access to that folder? it sounds like one of those isn't happening. Check the puid/guid settings, maybe you need to start the container using a different user.

which host system are you using?

**Comment by Bockiii** [comment]
@ma-karai ?

**Comment by ma-karai** [comment]
Sorry for the late reply :) its all writable and properly owned.

**Comment by ma-karai** [comment]
anything else i can troubleshoot?

**Comment by Bockiii** [comment]
This sounds to me like some config file can't be edited. Otherwise you shouldnt have to login everytime and changes to your config should actually persist :)

So I would maybe delete the whole config folder and recreate the container to let it create new files. That way you get rid of previous, possible misconfigurations (usually, the user access rights are the culprit).

Maybe your host OS is doing something weird? Which host do you use?

**Comment by Bockiii** [comment]
@ma-karai so?

**Comment by Bockiii** [comment]
you can reopen this if you find your misconfiguration
